apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  INVENTORY_SERVICE_URI: http://inventory-service:8081
  ORDER_SERVICE_URI: http://order-service:8082
  PRODUCT_SERVICE_URI: http://product-service:8083
  KAFKA_BOOTSTRAP: broker:9092

