apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-product
  name: db-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-product
  template:
    metadata:
      labels:
        app: db-product
    spec:
      containers:
        - image: mongo
          name: db-product
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-product-secrets
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-product-secrets
                  key: root-pwd
            - name: MONGO_INITDB_DATABASE
              value: "product-service"
          volumeMounts:
            - name: db-product-persistent-storage
              mountPath: /data/db
      volumes:
        - name: db-product-persistent-storage
          persistentVolumeClaim:
            claimName: db-product-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db-product
spec:
  selector:
    app: db-product
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-product-pvc
  labels:
    app: db-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
data:
  root-pwd: YWRtaW4=
  root-username: YWRtaW4=
kind: Secret
metadata:
  name: db-product-secrets