name: Workflow for Api Gateway
env:
  SERVICE: ApiGateway
on:
  push:
    branches: [ "main" ]
    paths:
      - "microservicetest/$SERVICE/**"
    
  pull_request:
    branches: [ "main" ]
    paths:
      - "microservicetest/$SERVICE/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Run Tests
      working-directory: ./${{ env.SERVICE }}
      run: mvn test
      
    - name: Build Docker image
      working-directory: ./${{ env.SERVICE }}
      run: docker build . -t ${{ env.SERVICE }}:${{ github.sha }}

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name : Tag Docker image
      working-directory: ./${{ env.SERVICE }}
      run: |
        docker tag ${{ env.SERVICE }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE }}:${{ github.sha }}
        docker tag ${{ env.SERVICE }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE }}:latest
        
    - name : Publish Docker image
      working-directory: ./${{ env.SERVICE }}
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE }}:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE }}:latest
      
     
          
    
